title: Hacker Handbook
description: A handbook for hackers
theme: jekyll-theme-midnight

github:
  repo_url: https://github.com/nancynobody/hacker_handbook

# plugins:
#  - jekyll-seo-tag
#  - jekyll-feed

collections:
  pages:
    output: true

header_pages:
  - pages/about.md

# Google Analytics (will only appear in production, i.e., JEKYLL_ENV=production)
google_analytics: UA-65929619-5